/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Vamsidhar' at '8/29/15 11:35 PM' with Gradle 2.5-rc-2
 *
 * @author Vamsidhar, @date 8/29/15 11:35 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
